customCommands:
  - key: "c"
    context: "files"
    prompts:
      - type: "input"
        title: "Add Commit Message"
        key: "Message"
    command: |
      branch=$(git rev-parse --abbrev-ref HEAD)
      prefix="$(echo "$branch" | sed -n 's|.*/\([A-Z][A-Z]*-[0-9][0-9]*\).*|\1 |p')"
      git commit -m "${prefix}{{.Form.Message}}"
    description: "Commit message with optional ticket number"
    output: terminal
  - key: "b"
    command: "git browse"
    context: "files"
    loadingText: "Opening repository in browser..."
    description: "Open repository in browser"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --diff-so-fancy
  overrideGpg: true
