# https://alacritty.org/config-alacritty.html

import = [
  "~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "SimpleFullscreen"
option_as_alt = "OnlyLeft"

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "MonaspiceNe Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "MonaspiceNe Nerd Font Mono"
style = "Regular Italic"

[font.italic]
family = "MonaspiceNe Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\uE000"

