# https://alacritty.org/config-alacritty.html

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"
dynamic_padding = false
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[window.padding]
x = 25
y = 20

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "Enter"
mods = "Command"
