# https://alacritty.org/config-alacritty.html

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "Buttonless"
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[window.padding]
x = 20
y = 40

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Thin Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Thin"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\uE000"

